targets:
  $default:
    sources:
      - lib/**
      - swagger/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: 'swagger/'
          output_folder: 'lib/swagger_generated_code/'
          with_base_url: true
          with_converter: true
          use_path_for_request_names: true
          include_null_query_vars: true
          use_default_null_for_lists: false
          override_equals_and_hashcode: true
          build_only_models: false
          separate_models: true
          enums_case_sensitive: false
          ignore_headers: false
          use_required_attribute_for_headers: false
          include_if_null: false
          default_values_map:
            - type_name: int
              default_value: '0'
            - type_name: String
              default_value: ''
            - type_name: 'List<String>'
              default_value: '[]'
